#!/usr/bin/env bash
set -euo pipefail

TARGET="windows"

usage() {
  cat <<'EOF'
Usage: scripts/parallels/setup.sh [options]

Options:
  --target <windows|linux>   Which local profile to write. Default: windows
  -h, --help                Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET="${2:?Missing value for --target}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$TARGET" != "windows" && "$TARGET" != "linux" ]]; then
  echo "--target must be 'windows' or 'linux'." >&2
  exit 2
fi

if ! command -v prlctl >/dev/null 2>&1; then
  echo "prlctl was not found. Install Parallels Desktop command-line tools." >&2
  exit 1
fi

vm_lines=()
while IFS= read -r line; do
  vm_lines+=("$line")
done < <(prlctl list --all --no-header)
if [[ "${#vm_lines[@]}" -eq 0 ]]; then
  echo "No registered Parallels VMs found. Create or register a VM first, then rerun this setup." >&2
  exit 1
fi

echo "Registered Parallels VMs:"
for index in "${!vm_lines[@]}"; do
  printf '  %d) %s\n' "$((index + 1))" "${vm_lines[$index]}"
done

read -r -p "Select VM number for ${TARGET}: " selection
if ! [[ "$selection" =~ ^[0-9]+$ ]] || (( selection < 1 || selection > ${#vm_lines[@]} )); then
  echo "Invalid selection: $selection" >&2
  exit 2
fi

selected_line="${vm_lines[$((selection - 1))]}"
vm_name="$(awk '{for (i=4; i<=NF; ++i) {printf "%s%s", (i == 4 ? "" : " "), $i}}' <<<"$selected_line")"
if [[ -z "$vm_name" ]]; then
  echo "Could not parse VM name from: $selected_line" >&2
  exit 1
fi

if [[ "$TARGET" == "windows" ]]; then
  default_repo='C:\Users\shane\Project\simplicity-engine'
  default_preset="debug"
  read -r -p "Windows repo path [${default_repo}]: " guest_repo
  read -r -p "CMake preset [${default_preset}]: " preset
  guest_repo="${guest_repo:-$default_repo}"
  preset="${preset:-$default_preset}"
  output="local/parallels/windows.env"
else
  default_repo="/home/shane/Project/simplicity-engine"
  default_preset="linux-debug"
  echo "Linux target selected. The documented package install commands assume an APT-based, Debian-compatible guest."
  read -r -p "Linux repo path [${default_repo}]: " guest_repo
  read -r -p "CMake preset [${default_preset}]: " preset
  guest_repo="${guest_repo:-$default_repo}"
  preset="${preset:-$default_preset}"
  output="local/parallels/linux.env"
fi

mkdir -p "$(dirname "$output")"
{
  printf '# Generated by scripts/parallels/setup.sh. This file is gitignored.\n'
  printf 'VM_NAME=%q\n' "$vm_name"
  printf 'GUEST_REPO=%q\n' "$guest_repo"
  printf 'PRESET=%q\n' "$preset"
} > "$output"

echo "Wrote ${output}"
