name: Nightly

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  linux-all-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runs_on: ubuntu-latest
          - arch: arm64
            runs_on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs_on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            xorg-dev \
            libasound2-dev \
            libpulse-dev \
            libudev-dev \
            libwayland-dev \
            libxkbcommon-dev \
            libdrm-dev \
            libgbm-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev

      - name: Configure (Release)
        run: cmake --preset release

      - name: Build (Release)
        run: cmake --build --preset release

      - name: All Tests (Release)
        run: ctest --test-dir build/release --output-on-failure
