name: Nightly

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  macos-all-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            runs_on: macos-latest
            cmake_arch: arm64
          - arch: x64
            runs_on: macos-latest
            cmake_arch: x86_64

    runs-on: ${{ matrix.runs_on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Ninja
        run: brew install ninja

      - name: Configure (Release)
        run: cmake --preset release -DCMAKE_OSX_ARCHITECTURES=${{ matrix.cmake_arch }}

      - name: Build (Release)
        run: cmake --build --preset release

      - name: All Tests (Release)
        run: ctest --test-dir build/release --output-on-failure
